
package ws.guiclient.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GameEngine", targetNamespace = "http://simpleworldgame.cs.bilkent.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GameEngine {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPLayers", targetNamespace = "http://simpleworldgame.cs.bilkent.edu/", className = "ws.guiclient.stubs.GetPLayers")
    @ResponseWrapper(localName = "getPLayersResponse", targetNamespace = "http://simpleworldgame.cs.bilkent.edu/", className = "ws.guiclient.stubs.GetPLayersResponse")
    @Action(input = "http://simpleworldgame.cs.bilkent.edu/GameEngine/getPLayersRequest", output = "http://simpleworldgame.cs.bilkent.edu/GameEngine/getPLayersResponse")
    public String getPLayers();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "activatePLayer", targetNamespace = "http://simpleworldgame.cs.bilkent.edu/", className = "ws.guiclient.stubs.ActivatePLayer")
    @ResponseWrapper(localName = "activatePLayerResponse", targetNamespace = "http://simpleworldgame.cs.bilkent.edu/", className = "ws.guiclient.stubs.ActivatePLayerResponse")
    @Action(input = "http://simpleworldgame.cs.bilkent.edu/GameEngine/activatePLayerRequest", output = "http://simpleworldgame.cs.bilkent.edu/GameEngine/activatePLayerResponse")
    public void activatePLayer(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registerPLayer", targetNamespace = "http://simpleworldgame.cs.bilkent.edu/", className = "ws.guiclient.stubs.RegisterPLayer")
    @ResponseWrapper(localName = "registerPLayerResponse", targetNamespace = "http://simpleworldgame.cs.bilkent.edu/", className = "ws.guiclient.stubs.RegisterPLayerResponse")
    @Action(input = "http://simpleworldgame.cs.bilkent.edu/GameEngine/registerPLayerRequest", output = "http://simpleworldgame.cs.bilkent.edu/GameEngine/registerPLayerResponse")
    public void registerPLayer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWorld", targetNamespace = "http://simpleworldgame.cs.bilkent.edu/", className = "ws.guiclient.stubs.GetWorld")
    @ResponseWrapper(localName = "getWorldResponse", targetNamespace = "http://simpleworldgame.cs.bilkent.edu/", className = "ws.guiclient.stubs.GetWorldResponse")
    @Action(input = "http://simpleworldgame.cs.bilkent.edu/GameEngine/getWorldRequest", output = "http://simpleworldgame.cs.bilkent.edu/GameEngine/getWorldResponse")
    public String getWorld();

}
